const {SlashCommandBuilder,PermissionFlagsBits}=require('discord.js');
const {getGuild,setGuild}=require('../database/firebase');
const {ok,fail,mod,admin,targetOK}=require('./factory');
function group(name,desc,subs){const b=new SlashCommandBuilder().setName(name).setDescription(desc);for(const s of subs)b.addSubcommand(s);return {data:b,execute:async i=>{const fn=subs._map[i.options.getSubcommand()];return fn(i)}}}
function sub(name,desc,add=()=>{}){const s={name,desc,add,run:null};return s}
function build(name,desc,list){const b=new SlashCommandBuilder().setName(name).setDescription(desc);for(const s of list)b.addSubcommand(x=>{x.setName(s.name).setDescription(s.desc);s.add(x);return x});return {data:b,execute:async i=>list.find(s=>s.name===i.options.getSubcommand()).run(i)}}
async function toggle(i,key){if(!admin(i))return fail(i,'Administrator permission required.');const g=await getGuild(i.guildId);g.settings=g.settings||{};g.settings[key]=!g.settings[key];await setGuild(i.guildId,g);return ok(i,key,`${g.settings[key]?'Enabled':'Disabled'}.`)}
const security=[sub('config','Show security settings'),sub('setmodrole','Set moderator role',x=>x.addRoleOption(o=>o.setName('role').setDescription('Role').setRequired(true))),sub('extraowner','Add an extra owner',x=>x.addUserOption(o=>o.setName('user').setDescription('User').setRequired(true))),sub('mainrole','Set main role',x=>x.addRoleOption(o=>o.setName('role').setDescription('Role').setRequired(true))),sub('adminrole','Set admin role',x=>x.addRoleOption(o=>o.setName('role').setDescription('Role').setRequired(true))),sub('antinuke','Toggle antinuke'),sub('antibot','Toggle anti-bot')];
security[0].run=async i=>{const g=await getGuild(i.guildId);return ok(i,'Security',JSON.stringify(g.settings?.security||{},null,2))};
for(const s of security.slice(1))s.run=async i=>{if(s.name==='setmodrole'||s.name==='mainrole'||s.name==='adminrole'){if(!admin(i))return fail(i,'Administrator permission required.');const g=await getGuild(i.guildId);g.settings=g.settings||{};g.settings[s.name]=i.options.getRole('role').id;await setGuild(i.guildId,g);return ok(i,s.name,`Set to <@&${i.options.getRole('role').id}>`)}if(s.name==='extraowner'){if(!admin(i))return fail(i,'Administrator permission required.');const g=await getGuild(i.guildId);g.extraOwners=g.extraOwners||[];const id=i.options.getUser('user').id;if(!g.extraOwners.includes(id))g.extraOwners.push(id);await setGuild(i.guildId,g);return ok(i,'Extra owner',`Added <@${id}>.`)}return toggle(i,`security.${s.name}`)};
const automod=['config','antispam','antilink','antibadwords','antizalgo','anticaps','whitelist'].map(n=>sub(n,`Manage ${n}`,n==='whitelist'?x=>x.addUserOption(o=>o.setName('user').setDescription('User')):()=>{}));
automod.forEach(s=>s.run=async i=>{if(s.name==='config'){const g=await getGuild(i.guildId);return ok(i,'Automod',JSON.stringify(g.settings?.automod||{},null,2))}return toggle(i,`automod.${s.name}`)});
const logs=['autologs','channellog','memberlog','messagelog','modlog','resetlog','rolelog','serverlog','showlogs','voicelog'].map(n=>sub(n,`Manage ${n}`));logs.forEach(s=>s.run=async i=>{if(s.name==='showlogs'){const g=await getGuild(i.guildId);return ok(i,'Logs',JSON.stringify(g.logs||{},null,2))}if(s.name==='resetlog'){if(!admin(i))return fail(i,'Administrator permission required.');const g=await getGuild(i.guildId);g.logs={};await setGuild(i.guildId,g);return ok(i,'Logs reset','Log configuration reset.')}return toggle(i,`logs.${s.name}`)});
const custom=['customrole','add','remove','list','reset','config','reqrole'].map(n=>sub(n,`Manage ${n}`,x=>n==='add'||n==='remove'?x.addRoleOption(o=>o.setName('role').setDescription('Role').setRequired(true)):x));custom.forEach(s=>s.run=async i=>{const g=await getGuild(i.guildId);if(s.name==='list')return ok(i,'Custom roles',(g.customRoles||[]).map(x=>`<@&${x}>`).join('\n')||'None');if(!admin(i))return fail(i,'Administrator permission required.');if(s.name==='reset'){g.customRoles=[];await setGuild(i.guildId,g);return ok(i,'Custom roles','Reset.')}if(s.name==='config'||s.name==='customrole'||s.name==='reqrole')return toggle(i,`custom.${s.name}`);const id=i.options.getRole('role').id;g.customRoles=g.customRoles||[];if(s.name==='add'&&!g.customRoles.includes(id))g.customRoles.push(id);if(s.name==='remove')g.customRoles=g.customRoles.filter(x=>x!==id);await setGuild(i.guildId,g);return ok(i,'Custom roles',`${s.name}: <@&${id}>`)});
function makeFeature(name,subs){return build(name,`Manage ${name}`,subs.map(n=>{const s=sub(n,`Manage ${n}`);s.run=async i=>{if(n==='config'){const g=await getGuild(i.guildId);return ok(i,name,JSON.stringify(g.modules?.[name]||{},null,2))}return toggle(i,`${name}.${n}`)};return s}))}
const giveaways=makeFeature('giveaway',['start','end','list','reroll']);
const autoresponder=makeFeature('autoresponder',['add','remove','list','test','reset']);
const welcomer=makeFeature('welcome',['setup','test','delete','list','keyword','reset','edit']);
const ticket=makeFeature('ticket',['panel','setup','list','reset','status']);
const sticky=makeFeature('sticky',['add','remove','list','reset']);
const selfrole=makeFeature('selfrole',['setup','list','delete','reset','cleanup','edit']);
const media=makeFeature('media',['channel','whitelist','reset']);
const autonick=makeFeature('autonick',['setup','config','reset']);
const autorole=makeFeature('autorole',['humans','bots','add','remove','list','reset']);
module.exports={security:build('security','Security controls',security),automod:build('automod','Automod controls',automod),logs:build('logs','Logging controls',logs),customrole:build('customrole','Custom roles',custom),giveaway:giveaways,autoresponder,ticket,welcome:welcomer,sticky,selfrole,media,autonick,autorole};
